# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- test

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  displayName: Get OWASP target context
  inputs:
    secureFile: 'Default Context.context'
 
- task: owaspzap@1
  inputs:
    scantype: 'targetedScan'
    url: 'https://polymath-lilith.azurewebsites.net/'
    provideCustomContext: true
    contextPath: './Default Context.context'
    threshold: 115
    port: '8080'
 
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      - bash: ' handlebars owaspzap/report.json < owaspzap/nunit-template.hbs > owaspzap/test-results.xml'
        displayName: 'generate nunit type file'
        condition: always()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: 'owaspzap/test-results.xml'
  condition: always()




